### ISSUE TITLE
 ERROR in ./node_modules/sanitize-html/node_modules/postcss/lib/input.js

### ISSUE THREAD

**Issue by solblog** [apostrophecms/sanitize-html#462] opened 2021-01-28 12:33 UTC
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

After instaling the next package:
"@types/sanitize-html": "1.27.0",
"sanitize-html": "2.2.0",

And in the Angular component import 

import sanitizeHtml from 'sanitize-html';

ngOnInit(): void {
    super.ngOnInit();
    const html = '<strong>hello world</strong>';
    console.log('sanitize', sanitizeHtml(html));
}

ERROR in ./node_modules/sanitize-html/node_modules/postcss/lib/input.js
Module not found: Error: Can't resolve 'path' in '<path>\node_modules\sanitize-html\node_modules\postcss\lib'

ERROR in ./node_modules/sanitize-html/node_modules/postcss/lib/previous-map.js
Module not found: Error: Can't resolve 'path' in '<path>\node_modules\sanitize-html\node_modules\postcss\lib'

ERROR in ./node_modules/sanitize-html/node_modules/postcss/lib/map-generator.js
Module not found: Error: Can't resolve 'path' in '<path>\node_modules\sanitize-html\node_modules\postcss\lib'

## Describe the bug
v10.20.1

Version of Node.js:
v10.20.1

**Server Operating System:**
Windows

**Additional context:**
Chrome

## Expected behavior:
Not throw the exception.

**Comment by abea** [comment] 2021-01-28 16:27
This looks to be a duplicate of https://github.com/apostrophecms/sanitize-html/issues/450. Please review that and comment if you have additional information.

**Closed by abea** 2021-01-28 16:27 UTC
Labels: bug
