### ISSUE TITLE
Can't resolve 'path'

### ISSUE THREAD

**Issue by mkrajcir** [apostrophecms/sanitize-html#451] opened 2021-01-11 07:41 UTC
I got an error with Angular 11 project

```
Error: ./node_modules/sanitize-html/node_modules/postcss/lib/input.js
Module not found: Error: Can't resolve 'path' in '/Users/mkrajcir/Devel/BMB/eshop/node_modules/sanitize-html/node_modules/postcss/lib'

Error: ./node_modules/sanitize-html/node_modules/postcss/lib/map-generator.js
Module not found: Error: Can't resolve 'path' in '/Users/mkrajcir/Devel/BMB/eshop/node_modules/sanitize-html/node_modules/postcss/lib'

Error: ./node_modules/sanitize-html/node_modules/postcss/lib/previous-map.js
Module not found: Error: Can't resolve 'path' in '/Users/mkrajcir/Devel/BMB/eshop/node_modules/sanitize-html/node_modules/postcss/lib'
```

**Comment by abea** [comment] 2021-01-11 15:08
Duplicate of #450. Please review that thread discussion and add additional information if possible.

**Closed by abea** 2021-01-11 15:08 UTC
Labels: bug
