### ISSUE TITLE
Error import sanitizeHtml

### ISSUE THREAD

**Issue by titobundy** [apostrophecms/sanitize-html#470] opened 2021-04-14 16:47 UTC
Hi, 

I installed sanitize-html but does not work when I use import, an error ocurrs when call **sanitizeHtml** function.

## To Reproduce

1. Create a project using Nest js CLI

2. Add package
yarn add sanitize-html 

3. Add package in a Class
import sanitizeHtml from 'sanitize-html'; 

## Expected behavior
It should work as stated in the documentation using:
`import sanitizeHtml from 'sanitize-html'; `

but for it to work correctly I must use (it took me a time to find this solution):
`import * as sanitizeHtml from 'sanitize-html';`

## Describe the bug
The error shows in console is _sanitize_html_1.default is not a function_ 

## Details
- NodeJS v12.20.0
- NestJS v7.5.4
- sanitize-html v2.3.3
- Linux Deepin 20.2

tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}
```

**Screenshots**
![Captura de pantalla_área-de-selección_20210414122933](https://user-images.githubusercontent.com/37158954/114746829-262d1300-9d1e-11eb-8dca-86791782e9a3.png)

**Comment by abea** [comment] 2021-04-21 22:19
Please check if this is a duplicate of #420

**Closed** 2021-05-18 21:46 UTC
Labels: bug
