### ISSUE TITLE
garbage text not cleaned up 

### ISSUE THREAD

**Issue by andpor** [apostrophecms/sanitize-html#164] opened 2017-09-19 11:24 UTC
I have a dirty html string that looks like this:

`"<html><body><p> some text </p></body></html> &%^junkunprintablecharshere"`

This string results from copy in MS outlook sometimes. I would expect sanitizeHtml to drop everything after closing `</html>` but it does not behave this way and I see the garbage chars after `</html>` returned as well. 

Is this by design and are there are ways to ensure clean html in returned i.e. all garbage after `</html>` is truncated when sanitizeHtml returns?

Many thanks.

**Comment by boutell** [comment] 2017-09-19 12:49
sanitize-html drops tags that are not on its allowed list. It doesn't view the "html" tag as a special case, mainly because we deal primarily with HTML fragments.

I can see why it would be reasonable to ignore any content after the close of an html tag, although for bc we'd want that to be an option. A PR would be welcome.

**Comment by andpor** [comment] 2017-09-19 17:52
i will give it a shot.. :)

**Comment by andpor** [comment] 2017-10-02 17:45
@boutell  PR created https://github.com/punkave/sanitize-html/pull/166

**Comment by andpor** [comment] 2017-10-13 15:30
PR updated.

**Comment by mikesamuel** [comment] 2017-10-20 16:22
I think this is a duplicate of [issue 149](https://github.com/punkave/sanitize-html/issues/149).

**Comment by andpor** [comment] 2017-10-20 16:44
Yes it is...

**Closed** 2020-05-27 20:15 UTC
