### ISSUE TITLE
Unclosed `<a>` tag breaks tag balance

### ISSUE THREAD

**Issue by fabiosantoscode** [apostrophecms/sanitize-html#79] opened 2015-11-10 12:51 UTC
This is a contrived example of some wild HTML that broke sanitize-html:

```
> sanitizeHTML('<p>Hey! Here is a broken link tag: <a href="http://www.example.com/lel...')
'<p>Hey! Here is a broken link tag: </a>'
```

I thought this was because it was in the middle of a string, but it actually triggers if the string ends in the middle of any part of the attribute. But not if the tag doesn't have attributes yet!

```
> sanitizeHTML('<p>lel <a')
'<p>lel </p>'  // good
> sanitizeHTML('<p>lel <a href')
'<p>lel </a>'  // bad!
> sanitizeHTML('<p>lel <a href=""')
'<p>lel </a>'  // bad!
```

**Comment by boutell** [comment] 2015-11-10 13:25
This is an upstream bug in htmlparser2, there is probably no sensible workaround so I've reported it there.

**Comment by fabiosantoscode** [comment] 2015-11-10 13:39
Okay, thank you :)

**Comment by ElegantScripting** [comment] 2016-01-19 00:43
What's the story with this bug?

**Comment by boutell** [comment] 2016-01-19 00:47
Upstream bug, no fix yet:

https://github.com/fb55/htmlparser2/issues/156

**Comment by BenLubar** [comment] 2016-02-29 04:54
It's more dangerous than just closing allowed tags. It works with any tag, including malformed tag names like this:

```
<html<script
```

Which results in the "sanitized" version being `</html<script>`.

**Comment by BenLubar** [comment] 2016-02-29 13:52
I can't reproduce this bug with the current git master versions of htmlparser2 and sanitize-html.

**Comment by fabiosantoscode** [comment] 2016-02-29 14:15
Interesting. I can reproduce it with the following steps:

```
fabio@thinkpadlel ♥  git clone git@github.com:punkave/sanitize-html.git
[...]
fabio@thinkpadlel ♥  cd sanitize-html/
fabio@thinkpadlel ♥  npm i
[...]
fabio@thinkpadlel ♥  node
> require('.')('<p>Hey! Here is a broken link tag: <a href="http://www.example.com/lel...')
'<p>Hey! Here is a broken link tag: </a>'
> fabio@thinkpadlel ♥  cd node_modules/
fabio@thinkpadlel ♥  rm -rf htmlparser2/
fabio@thinkpadlel ♥  git clone git@github.com:fb55/htmlparser2.git
[...]
fabio@thinkpadlel ♥  node
> require('.')('<p>Hey! Here is a broken link tag: <a href="http://www.example.com/lel...')
'<p>Hey! Here is a broken link tag: </a>'

```

**Comment by BenLubar** [comment] 2016-02-29 14:45
Oh, I was on an ancient version (0.1.4) and it had this bug without attributes (`<div` would break it). I just checked and can confirm that the test case given in the OP is still an issue.

**Comment by fabiosantoscode** [comment] 2016-02-29 14:50
Different variations of the same problem:

```
> require('.')('<p>Hey! Here is a broken link tag: <a href="')
'<p>Hey! Here is a broken link tag: </a>'
> require('.')('<p>Hey! Here is a broken link tag: <a href=')
'<p>Hey! Here is a broken link tag: </a>'
> require('.')('<p>Hey! Here is a broken link tag: <a href')
'<p>Hey! Here is a broken link tag: </a>'
> require('.')('<p>Hey! Here is a broken link tag: <a ')
'<p>Hey! Here is a broken link tag: </a>'
> require('.')('<p>Hey! Here is a broken link tag: <a')
'<p>Hey! Here is a broken link tag: </p>'
> 
```

**Comment by ElegantScripting** [comment] 2016-03-01 04:00
This is a pretty big upstream bug.

**Comment by boutell** [comment] 2016-03-01 04:46
Yes, yes it is. I'd like to find some time to bang on it myself.

On Mon, Feb 29, 2016 at 11:00 PM, ElegantScripting <notifications@github.com
> wrote:

> This is a pretty big upstream bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/79#issuecomment-190528994>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2016-03-01 12:45
I just submitted a PR upstream with a fix for this.

On Mon, Feb 29, 2016 at 11:46 PM, Tom Boutell <tom@punkave.com> wrote:

> Yes, yes it is. I'd like to find some time to bang on it myself.
>
> On Mon, Feb 29, 2016 at 11:00 PM, ElegantScripting <
> notifications@github.com> wrote:
>
>> This is a pretty big upstream bug.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/sanitize-html/issues/79#issuecomment-190528994>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by markdowney** [comment] 2018-07-19 15:49
Note that this is not limited to the `<a>` tag. Basically any combination of (less than)+(char) will delete everything starting with (less than).

```sanitizeHtml('1+1<3')```
> ```1+1```

This seems quite critical. Any reason the upstream fix has not been accepted?

**Comment by boutell** [comment] 2018-07-19 17:01
I fixed it in the wrong layer apparently.

**Comment by ybrodsky** [comment] 2019-06-06 15:18
Whatever happened to this?
If you have a string of the sort `some text <3 some more text` you end up getting an output `some text`.

**Comment by boutell** [comment] 2019-06-06 15:46
It is an upstream bug in htmlparser2. At one point I submitted a PR but it was not to the API layer the developer preferred. I haven't had time to work on it since. Contributions are welcome.

**Comment by abea** [comment] 2020-05-28 20:48
This looks to be resolved, per https://github.com/fb55/htmlparser2/issues/156#issuecomment-590067942

**Closed by abea** 2020-05-28 20:48 UTC
