### ISSUE TITLE
transformTags return double text when changing text of tag that already have text

### ISSUE THREAD

**Issue by newz** [apostrophecms/sanitize-html#136] opened 2016-12-18 16:43 UTC
Example.
```
var sanitizeHtml = require("sanitize-html");

var clean = sanitizeHtml('Go to <a href="https://www.google.com">Google</a>', {
  transformTags: {
    'a': function(tagName, attribs) {
        return {
            tagName: 'a',
            text: 'Github',
            attribs: {
                href: "https://www.github.com"
            }
        };
    }
  }
});

console.log(clean);
```
will result in
```
Go to <a href="https://www.github.com">GithubGithub</a>
```

You can see that transformTags return Github twice.

Runkit url
https://runkit.com/5856b06df18eae0013bcf2da/5856b974001b65001374e127

**Comment by halffullheart** [comment] 2017-02-07 02:17
Experiencing the same issue.

**Comment by george-norris-salesforce** [comment] 2017-03-13 21:30
Me too

**Comment by civalin** [comment] 2017-04-20 01:43
me too

# example

```javascript
var sanitizeHtml = require('sanitize-html');
sanitizeHtml('x<a>y</a>', { transformTags: { a: () => { return { tagName: 'div', text: 'z' }; } }});
```

the result is:

```
'x<div>zz</div>'
```

(expect `'x<div>z</div>'`)

# version info

- sanitize-html@1.14.1
- node.js 6.10.2

**Comment by andpor** [comment] 2017-10-17 09:37
This is definitely a defect. I can reproduce it easily with 1.14.1. Actually the unit test case will fail as well. This works fine if returned text is empty string or a single space: '' or ' ' - duplicate does not occur for these values.

**Comment by andpor** [comment] 2017-10-17 09:45
This is unit test case. Currently it is not failing because text returned from transformTags is empty string, but if it is slightly changed to return value "google.com" the output is duplicated.

`
```
it('should replace text and attributes when they are changed by transforming function', function () {
    assert.equal(sanitizeHtml('<a href="http://somelink">some text</a>', { transformTags: {a: function (tagName, attribs) {
      return {
        tagName: tagName,
        attribs: attribs,
        text: 'google.com'
      }
    }}}), '<a href="http://somelink">google.com</a>');
  });
`

```
65 passing (12s)
  1 failing

  1) sanitizeHtml should replace text and attributes when they are changed by transforming function:

      AssertionError: '<a href="http://somelink">google.comgoogle.com</a>' == '<a href="http://somelink">google.com</a>'
      + expected - actual

      -<a href="http://somelink">google.comgoogle.com</a>
      +<a href="http://somelink">google.com</a>
      
      at Context.<anonymous> (test/test.js:127:12)

```
```

**Comment by andpor** [comment] 2017-10-17 10:11
These is the line causing the duplication. 

This is inside onopentag() callback so we have not received the text for the tag yet. Therefore frame.innerText will be TRUE, since we return non-empty string,
hasText will be false since we have not received text for this tag yet, and textFilter has not been provided for this execution. Compound if statement will evaluate to true append the text returned from transformTags and later in ontext() callback it will be appended again.

There should be no code looking at frame's text in onopentag...this is the issue...

https://github.com/punkave/sanitize-html/blob/1d78daeaf2fd49ba66beb6c287017af2cee7b636/index.js#L194

        if (frame.innerText && !hasText && !options.textFilter)

**Comment by andpor** [comment] 2017-10-17 10:57
This defect is getting more and more interesting. The following code will produce a very weird result:

`"Go to here <a href=\"https://www.github.com\">testtestmetest</a>"`


```

sanitizeHtml('Go to here <a href="https://www.google.com">Google<span>me</span>someother text</a>', {
  transformTags: {
    'a': function(tagName, attribs) {
        return {
            tagName: 'a',
            text: 'test',
            attribs: {
                href: "https://www.github.com"
            }
        };
    }
  }
});
```

The problem is that ontext() gets invoked every time there is a text element directly inside the tag. Each time it is invoked, if there was anything returned from onTransformTags for that tag, that value will be used and returned...resulting in multiple duplications...

**Comment by skeddles** [comment] 2019-06-26 19:52
2019, tried to start using this package but ran into this issue. Is there a way around or a fix in the near future?

`console.log(,sanitizeHtml('<b>hi</b>', {transformTags: {b: ()=>{return {tagName: 'b',text: 'bye'}}}}));`
output: '<b>byebye</b>'

**Comment by abea** [comment] 2020-08-06 22:57
Sorry for the looong delay. A fix is in a PR for the 1.x and 2.x versions.

**Closed** 2020-08-07 15:03 UTC
Labels: bug
