### ISSUE TITLE
Identifying bare text

### ISSUE THREAD

**Issue by jmjf** [apostrophecms/sanitize-html#109] opened 2016-05-19 15:33 UTC
I'm processing input pasted from Word into a rich text edit control. Word produces HTML similar to:

```
<p><span>abc</span><p>
<span>def</span>
```

Desired output

```
<p>abc</p>
<p>def</p>
```

The simple solution seems to be to call sanitize twice--eliminate do-nothing `<span>`s in pass one and wrap the resulting untagged text in `<p>` in pass two. After getting very close to perfect by detecting leading `\n` on untagged text, I still have a common edge case where I get a `<span>` of text, no other HTML, no leading `\n`. This gives me untagged text I can't detect from the text alone.

Untagged text goes to textFilter only (as far as I can tell), but textFilter doesn't know the text is untagged. If textFilter knew the text's frame, it could recognize an undefined frame and know it was dealing with untagged text that needs special handling. Knowing the text's frame would also allow people to implement more versatile text filters for specific tags.

Am I missing an option that handles the untagged text case?

If not, would you accept a PR that passes the frame (lastFrame from ontext) as a second argument to textFilter? (I'm proposing passing as the second argument to avoid breaking existing code.)

Thanks.

**Comment by abea** [comment] 2020-05-28 21:12
This is a duplicate of https://github.com/apostrophecms/sanitize-html/issues/268. Or actually that is a duplicate of this. Sorry for the delay.

**Closed by abea** 2020-05-28 21:12 UTC
