### ISSUE TITLE
discard ignore

### ISSUE THREAD

**Issue by usb248** [apostrophecms/sanitize-html#408] opened 2020-09-02 22:28 UTC
## Expected behavior
discard tags

## Describe the bug
tags not removed
input : `<strong>strong</strong>`
ouput : `&lt;strong&gt;strong&lt;/strong&gt;`

should be `strong`

## Details
```js
sanitizeHtml("<strong>strong</strong>", {
    allowedTags: []
})
```

**Version of Node.js:**
12.x

**Server Operating System:**
Windows

**Comment by boutell** [comment] 2020-09-03 11:21
I am unable to reproduce this with this test in either 1.x or 2.x rc:

```
  it('should discard disallowed tags by default', function() {
    assert.equal(sanitizeHtml('<strong>strong</strong>', { allowedTags: [] }), 'strong');
  });
```

I think you might be leaving something out of your example. 

Closing for now, as it does not appear to be reproducible. But please submit a PR with a failing test if you are able to reproduce it.

**Closed by boutell** 2020-09-03 11:21 UTC
Labels: bug
